# Generated by Django 3.1.7 on 2021-09-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    sql = """
create view api_display as 
select u.*, 
	ss.start_at,
	ss.estimated_end_at,
	ss.end_at
from api_user as u
left join (
	select m.*
	from api_study as m
	where not exists (
	    select 1
	    from api_study as s
	    where m.user_id = s.user_id
	    and m.start_at < s.start_at
	)
) as ss on u.id = ss.user_id
order by u.subject , u.name;
    """

    reverse_sql = """
            DROP VIEW IF EXISTS api_display;
        """

    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
