# Generated by Django 5.0.4 on 2024-05-05 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('emote', models.CharField(max_length=10, null=True)),
                ('chara', models.CharField(max_length=10, null=True)),
                ('place', models.CharField(max_length=10, null=True)),
                ('subject', models.CharField(default='指定なし', max_length=100)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_end_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'api_display',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('emote', models.CharField(max_length=10, null='smile')),
                ('chara', models.CharField(default='zunda', max_length=10)),
                ('place', models.CharField(default='休憩所', max_length=10)),
                ('subject', models.CharField(default='指定なし', max_length=100)),
                ('comment', models.CharField(default='がんばります', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_end_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arg1', models.CharField(max_length=100, null=True)),
                ('arg2', models.CharField(max_length=100, null=True)),
                ('arg3', models.CharField(max_length=100, null=True)),
                ('arg4', models.CharField(max_length=100, null=True)),
                ('executed_unity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
