# Generated by Django 5.0.4 on 2024-05-11 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('emote', models.CharField(default='Charge', max_length=10)),
                ('chara', models.CharField(default='Colobus', max_length=10)),
                ('place', models.CharField(default='Z', max_length=10)),
                ('subject', models.CharField(default='指定なし', max_length=100)),
                ('comment', models.CharField(default='っがんばります!!', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_end_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=400)),
                ('command_name', models.CharField(max_length=100)),
                ('arg1', models.CharField(max_length=100, null=True)),
                ('arg2', models.CharField(max_length=100, null=True)),
                ('arg3', models.CharField(max_length=100, null=True)),
                ('arg4', models.CharField(max_length=100, null=True)),
                ('executed_unity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
